# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - @adviser/drizzle-orm

permissions:
  id-token: write

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false
          version: 8

      - name: Clone Drizzle Fork ${{ env.GITHUB_REF }}
        run: |
          git clone -b simple-iterator https://github.com/mabels/drizzle-orm.git drizzle-orm

      - name: Patch Version ${{ env.GITHUB_REF }}
        run: |
          cd drizzle-orm/drizzle-orm
          node ../../.github/workflows/patch-package.json.js "$GITHUB_REF"
          git diff

      - name: Build Version ${{ env.GITHUB_REF }}
        run: |
          cd drizzle-orm/drizzle-orm
          pnpm install
          pnpm run build
          pnpm run test
          pnpm run test:types
          pnpm run pack

      - uses: mabels/neckless@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: v0.1.16

      - name: Publish runified NPM
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
        run: |
            eval $(neckless kv ls --shKeyValue --ghAddMask NPM_PASS  NPM_USER "NPM_TOTP@Totp()")
            # env | sort | grep NPM
            token=$(curl -H "npm-otp: $NPM_TOTP" \
                 -X PUT \
                 -H 'content-type: application/json' \
                 -d "{\"name\":\"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
                 https://registry.npmjs.org/-/user/org.couchdb.user:$NPM_USER | jq -r .token)
            echo "//registry.npmjs.org/:_authToken=$token" > $HOME/.npmrc
            cd drizzle-orm/drizzle-orm
            npm publish \
               --provenance \
               --otp=$(neckless kv ls --onlyValue "NPM_TOTP@Totp()") \
               --access public --no-git-checks package.tgz
